import = ["~/.config/alacritty/themes/nord.toml"]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "zellij"]

[window]
option_as_alt = "Both"
dimensions = { columns = 172, lines = 46 }

padding.x = 5
padding.y = 5

[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

[font.offset]
x = 0
y = 1

[keyboard]
bindings = [
    # { key = "Right", mods = "Alt", chars = "\u001BF" },
    # { key = "Left", mods = "Alt", chars = "\u001BB" },
]
